FROM docker.io/openjdk:11.0.16-jdk
MAINTAINER "gkim" <guardkim9@nate.com>

ENV JAVA_OPTS="-server -Xms128M -Xmx256M" \
    JAVA_OPTS_APPEND="-XX:+UseG1GC" \
    CLASSPATH="${JAVA_HOME}/lib;." 
COPY basic-springboot-276/build/libs/ .

CMD java -jar *.jar
